### ISSUE TITLE
crypto_sign_SECRETKEYBYTES is now 64 bytes

### ISSUE THREAD

**Issue by jedisct1** [Asmod4n/mruby-libhydrogen#2]
Hi!

Just to let you know that secret keys for signatures now include a copy of the public key, similar to NaCl/libsodium.

This avoids an extra multiplication for each signature, and mitigates misuse by using the wrong public key for a given secret key.

But as a result, the size of these keys have doubled. This has probably a couple implications for mruby-libhydrogen.

**Comment by Asmod4n** [comment]
Should "only" have consequenzes for endusers, mruby-libhydrogen is using the constants which are defined in libhydrogen

**Comment by jedisct1** [comment]
Perfect! Nothing to change on your end, then :)

Thanks!

**Comment by jedisct1** [comment]
Do you think you could update the submodule?

I'm gonna give a talk about it next week :)
